Repository velenyx/feedback-app, pull requests merged in 2023-09, with the labels that each got.

#8 Feature/registration
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/Routing.tsx
  client/src/app/styles/libs/_normalize.scss
  client/src/app/styles/libs/_variables.scss
  client/src/components/BurgerMenu/BurgerMenu.module.scss
  client/src/components/BurgerMenu/BurgerMenu.tsx
  client/src/components/Footer/Footer.module.scss
  client/src/components/Footer/Footer.tsx
  client/src/components/FormRegister/FormRegister.module.scss
  client/src/components/FormRegister/FormRegister.tsx
  client/src/components/Header/Header.module.scss
  client/src/components/Header/Header.tsx
  client/src/components/NavItem/NavItem.module.scss
  client/src/components/NavItem/NavItem.tsx
  client/src/pages/Register/Register.module.scss
  client/src/pages/Register/Register.tsx
  client/src/pages/Register/api/index.ts
  client/src/pages/Register/types/index.ts
  client/src/shared/assets/logo.png
  client/src/shared/config/routePath.ts
  client/src/shared/helpers/capitalizeFullName.ts
  client/src/shared/helpers/errorMessageTranslate.ts
  client/src/shared/hooks/useAuth.ts
  client/src/shared/ui/Buttons/AuthButton.module.scss
  client/src/shared/ui/Buttons/AuthButton.tsx
  package-lock.json
  package.json
Labels: enhancement

#27 feat: ✨ pull request helper in github actions
  .github/workflows/pr-helper.yml
Labels: auto-merge, review-required

#21 Feature/feedback delete
  server/.eslintrc.json
  server/src/controllers/category.controller.js
  server/src/controllers/feedback.controller.js
  server/src/routes/v1/feedback.route.js
  server/src/routes/v1/index.js
  server/src/services/feedback.service.js
  server/src/validations/categories.validation.js
  server/tests/fixtures/categories.fixture.js
  server/tests/integration/categories.test.js
  server/tests/integration/docs.test.js
Labels: auto-merge
